import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import CartProvider from "@/components/layout/Provider";
import ShoppingCartModal from "@/components/layout/shoppingCartMoal"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
          <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CartProvider>
          <ShoppingCartModal/>
          {children}
          <Footer />
          </CartProvider>
        </body>
      </html>
  );
}
function Geist({ variable, subsets }: { variable: string; subsets: string[]; }) {
  return { variable, subsets };
}

